"""Generate a professional PDF strategy report using ReportLab."""
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ------------------------------------------------------------------ #
#  Colour palette                                                      #
# ------------------------------------------------------------------ #
NAVY = colors.HexColor("#1e3a5f")
BLUE = colors.HexColor("#2e5d8e")
LIGHT_BLUE = colors.HexColor("#e8f0fb")
GREY = colors.HexColor("#555555")
LIGHT_GREY = colors.HexColor("#f7f7f7")


def _build_styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle("ReportTitle", parent=styles["Title"],
        fontSize=26, textColor=NAVY, alignment=TA_CENTER, spaceAfter=6))

    styles.add(ParagraphStyle("ReportSubtitle", parent=styles["Normal"],
        fontSize=12, textColor=GREY, alignment=TA_CENTER, spaceAfter=4))

    styles.add(ParagraphStyle("SectionHeading", parent=styles["Heading1"],
        fontSize=16, textColor=NAVY, spaceBefore=16, spaceAfter=8))

    styles.add(ParagraphStyle("SubHeading", parent=styles["Heading2"],
        fontSize=13, textColor=BLUE, spaceBefore=12, spaceAfter=6))

    styles.add(ParagraphStyle("BodyText2", parent=styles["Normal"],
        fontSize=10, leading=15, spaceAfter=6, alignment=TA_JUSTIFY))

    styles.add(ParagraphStyle("BulletText", parent=styles["Normal"],
        fontSize=10, leading=14, spaceAfter=4,
        leftIndent=16, firstLineIndent=-8))

    styles.add(ParagraphStyle("Footer", parent=styles["Normal"],
        fontSize=8, textColor=GREY, alignment=TA_CENTER))

    return styles


def _render_content(text: str, styles) -> list:
    """Convert markdown-ish text into ReportLab flowables."""
    elements: list = []
    if not text:
        return elements

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            elements.append(Spacer(1, 4))
            continue

        if line.startswith("### "):
            elements.append(Paragraph(line[4:], styles["SubHeading"]))
        elif line.startswith("## "):
            elements.append(Paragraph(line[3:], styles["SubHeading"]))
        elif line.startswith("# "):
            elements.append(Paragraph(line[2:], styles["SectionHeading"]))
        elif line.startswith(("- ", "* ", "• ", "● ")):
            body = line[2:].strip()
            # Bold the label before a colon if present
            if ":" in body and body.index(":") < 40:
                label, rest = body.split(":", 1)
                body = f"<b>{label}</b>:{rest}"
            elements.append(Paragraph(f"&nbsp;&nbsp;• {body}", styles["BulletText"]))
        elif line.startswith(tuple(f"{i}." for i in range(1, 20))):
            elements.append(Paragraph(line, styles["BulletText"]))
        else:
            # Bold **text**
            line = line.replace("**", "<b>", 1).replace("**", "</b>", 1) if "**" in line else line
            elements.append(Paragraph(line, styles["BodyText2"]))

    return elements


def _add_section(title: str, key: str, report_data: dict, styles, elements: list) -> None:
    content = report_data.get(key, "")
    if not content:
        return

    elements.append(Paragraph(title, styles["SectionHeading"]))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=BLUE))
    elements.append(Spacer(1, 0.3 * cm))
    elements.extend(_render_content(content, styles))


def generate_pdf_report(report_data: dict) -> bytes:
    """Return the PDF report as raw bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2.2 * cm,
        leftMargin=2.2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
        title="Product Strategy Report",
        author="AI Product Strategy Assistant",
    )

    styles = _build_styles()
    elements: list = []

    # ---- Cover ---- #
    elements.append(Spacer(1, 2.5 * cm))
    elements.append(Paragraph("AI-Powered Product Strategy Report", styles["ReportTitle"]))
    elements.append(Spacer(1, 0.4 * cm))
    elements.append(Paragraph("Generated by the Multi-Agent Product Strategy Assistant", styles["ReportSubtitle"]))
    elements.append(Paragraph(f"Report Date: {datetime.now().strftime('%B %d, %Y')}", styles["ReportSubtitle"]))
    elements.append(Spacer(1, 0.8 * cm))
    elements.append(HRFlowable(width="100%", thickness=2.5, color=NAVY))
    elements.append(Spacer(1, 1.5 * cm))

    # ---- Table of Contents ---- #
    toc_rows = [
        ["#", "Section"],
        ["1", "Executive Summary"],
        ["2", "Customer Insights Report"],
        ["3", "Market Research Summary"],
        ["4", "Competitor Analysis Report"],
        ["5", "SWOT Analysis"],
        ["6", "Feature Prioritization Recommendations"],
        ["7", "Strategic Recommendations & Action Plan"],
    ]
    toc_table = Table(toc_rows, colWidths=[1.2 * cm, 14 * cm])
    toc_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREY]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.lightgrey),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
    ]))
    elements.append(Paragraph("Table of Contents", styles["SectionHeading"]))
    elements.append(toc_table)
    elements.append(PageBreak())

    # ---- Sections ---- #
    sections = [
        ("1. Executive Summary", "executive_summary"),
        ("2. Customer Insights Report", "customer_insights"),
        ("3. Market Research Summary", "market_research"),
        ("4. Competitor Analysis Report", "competitor_analysis"),
        ("5. SWOT Analysis", "swot_analysis"),
        ("6. Feature Prioritization Recommendations", "feature_priorities"),
        ("7. Strategic Recommendations & Action Plan", "strategy_recommendations"),
    ]

    for i, (title, key) in enumerate(sections):
        _add_section(title, key, report_data, styles, elements)
        if i < len(sections) - 1:
            elements.append(PageBreak())

    # ---- Footer note ---- #
    elements.append(Spacer(1, 1 * cm))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey))
    elements.append(Spacer(1, 0.2 * cm))
    elements.append(Paragraph(
        "This report was automatically generated by the AI-Powered Product Strategy Assistant. "
        "Insights are derived from the provided data and should be reviewed by relevant stakeholders "
        "before finalising strategic decisions.",
        styles["Footer"],
    ))

    doc.build(elements)
    return buffer.getvalue()
